version: '2'
services:
  knote:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000"
  nginx_proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs/localhost.crt:/etc/nginx/localhost.crt:ro
      - ./nginx/certs/localhost.key:/etc/nginx/localhost.key:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - knote

